networks:
  portfolio_net:
    driver: bridge

services:
  portfolio:
    image: docker-repo.jacobjones.com.au/portfolio:latest
    container_name: portfolio
    restart: always
    env_file:
      - .env
    networks:
      - portfolio_net
    # no expose needed

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: always
    ports:
      - "85:80"   # Only nginx is reachable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - portfolio
    networks:
      - portfolio_net